#include "chowdsp_presets_v2.h"

#include "Backend/chowdsp_Preset.cpp"
#include "Backend/chowdsp_PresetState.cpp"
#include "Backend/chowdsp_PresetTree.cpp"
#include "Backend/chowdsp_PresetSaverLoader.cpp"
#include "Backend/chowdsp_PresetManager.cpp"

#include "Frontend/chowdsp_PresetsProgramAdapter.cpp"
#include "Frontend/chowdsp_PresetsNextPreviousInterface.cpp"
#include "Frontend/chowdsp_PresetsTextInterface.cpp"
#include "Frontend/chowdsp_PresetsMenuInterface.cpp"
#include "Frontend/chowdsp_PresetsFileInterface.cpp"
#include "Frontend/chowdsp_PresetsClipboardInterface.cpp"
#include "Frontend/chowdsp_PresetsSettingsInterface.cpp"
