name: CMake

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test module on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9

    - name: Get latest CMake
      uses: lukka/get-cmake@latest 

    - name: Set up environment
      # working-directory: ${{github.workspace}}
      run: |
        git clone --depth 1 --branch 6.0.1 https://github.com/juce-framework/JUCE.git
        mkdir JUCE_modules && cd JUCE_modules
        git clone --single-branch --branch chowdsp https://github.com/Chowdhury-DSP/foleys_gui_magic.git

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/JUCE_modules
        clean: false

    - name: Cache juceaide
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/JUCE_modules/chowdsp_utils/build/JUCE/tools
        key: ${{ runner.os }}-juceaide

    - name: Configure
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        cd JUCE_modules/chowdsp_utils
        ls
        cmake -Bbuild

    - name: Build
      working-directory: ${{github.workspace}}/JUCE_modules/chowdsp_utils/build
      shell: bash
      run: cmake --build . --parallel

    - name: Test
      working-directory: ${{github.workspace}}/JUCE_modules/chowdsp_utils/build
      run: ctest -C Debug -V     
