name: Docs

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  WORK_DIR: ${{github.workspace}}/JUCE_modules/chowdsp_utils

jobs:
  build_and_test:
    if: contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Make and deploy docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt install doxygen graphviz

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{env.WORK_DIR}}

    - name: Make Docs
      working-directory: ${{env.WORK_DIR}}/doxygen
      run: make

    - name: Deploy docs
      if: ${{ github.event_name != 'pull_request' }}
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ${{env.WORK_DIR}}/docs
        remote: Library/Web/chowdsp/chowdsp_utils
        host: ccrma-gate.stanford.edu
        username: jatin
        password: ${{ secrets.CCRMA_PASS }}
